### ISSUE TITLE
Inconsistent docs for parameters to arg routines

### ISSUE THREAD

**Issue by djerius** [exodist/Declare-CLI#2]
The synopsis indicates that three parameters are passed to the `arg` routines: `$self`, `$opts`, `$args`.  In one instance the synopsis shows:

```
arg filter => sub {
    my $self = shift;
    my ( $opts, $args ) = @_;
    my $types = { map { $_ => 1 } @{ $opts->{types}} };
```

However, in this case `$opts` is equal to the scalar "filter", it's not a hash with key `types`.  That's what is in `$args`.

It's not clear what `$opts` and `$args` are.

Thanks,

Diab

**Comment by exodist** [comment]
Thanks for the report!  When I have a chance I will try to sort it out. If you wanted to look at the code and figure it out I would happily accept a pull request to fix the docs!
